---
title: "Zadanie 1"
author: "Kacper Siemaszko"
date: "October 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(SmarterPoland)
library(dplyr)
library(gridExtra)
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
mieszkania <- read.csv(file = "https://raw.githubusercontent.com/STWUR/STWUR-2017-06-07/master/data/mieszkania_dane.csv", 
                       encoding = "UTF-8") %>% 
  na.omit
```

## Zadanie I

Na jednym wykresie przedstaw rozklad cen i wieku mieszkan dla a) calego Wroclawia b) poszczegolnych dzielnic.

```{r zadanie_I, echo = FALSE, fig.width = 15}

w2 <- ggplot(data = mieszkania, aes(x = rok, y = cena_m2*metraz, fill = dzielnica)) +
  stat_density_2d(aes(alpha = ..level..), color = "black", contour = TRUE, geom = "polygon") +
  facet_wrap(~ dzielnica)

w1 <- ggplot(data = mieszkania, aes(x = rok, y = cena_m2*metraz)) +
  stat_density_2d(aes(alpha = ..level..), color = "black", contour = TRUE, geom = "polygon")

grid.arrange(w1, w2, nrow = 1)
```

## Zadanie II

Przedstaw zaleznosc ceny za metr^2 od dzielnicy, pietra i roku zbudowania mieszkania.

```{r zadanie_II, echo=FALSE, fig.width = 15, fig.height = 15}
plot.by.dzielnica <- function(x) ggplot(mieszkania[mieszkania$dzielnica==x,], aes(x = rok, y = cena_m2, fill = dzielnica, color = cut(pietro, breaks = c(-1,4,8,12, 16)))) +
  scale_x_continuous(limits = c(min(mieszkania$rok), max(mieszkania$rok))) +
  scale_y_continuous(limits = c(min(mieszkania$cena_m2), max(mieszkania$cena_m2))) +
  geom_point(alpha = 0.8) + 
  facet_wrap(~cut(pietro, breaks = c(-1,4,8,12, 16)), drop = FALSE, nrow = 1)

grid.arrange(grobs = lapply(unique(mieszkania$dzielnica), plot.by.dzielnica),ncol = 1)
```
