---
title: "Sondaz"
author: "Olaf Werner"
date: "October 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```
##Wykres stworzony na podstawie [Gazety Wyborczej](http://wyborcza.pl/1,75398,19061937,tns-dla-wyborczej-w-nowym-sejmie-trzy-czy-siedem-partii.html)

```{r}
library(ggplot2)
dane<-data.frame(nazwa=factor(c("PiS","PO","K'15","ZL",".N","K","PSL"),levels = c("PiS","PO","K'15","ZL",".N","K","PSL")),
                 procenty=c(32.5,26.3,10.4,7.5,6.1,5.3,4.8))
ggplot(dane,aes(x=nazwa,y=procenty,fill=nazwa)) + geom_col(width=0.7) + 
  geom_text(aes(label=as.character(procenty),y=procenty+1),size=5,fontface="bold") + guides(fill=FALSE) + 
  coord_fixed(ratio = 0.25) +
  labs(title="POPARCIE DLA PARTII",y="",x="",subtitle="(W PROC.)") +
  theme_minimal()+theme(panel.border = element_blank(),
                        panel.grid.major = element_blank(),
                        panel.grid.minor = element_blank(),
                        axis.text.y = element_blank(),
                        axis.text = element_text(face = "bold",size = rel(1.5)),
                        plot.title = element_text(size = rel(1.75),hjust=-.1,face="bold")
                        
                        )
```



