---
title: "Techniki wizualizacji danych - Praca domowa nr 1"
author: "Piotr Halama"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(reshape2)
```

# Wyniki wyborów do bawarskiego landtagu

Dane zostały pozyskane z: [link do artykułu](https://www.osw.waw.pl/pl/publikacje/analizy/2018-10-15/wybory-landowe-w-bawarii-porazka-csu-i-spd-tryumf-zielonych).

Poniższy wykres porównuje wyniki wyborów w Bawarii w roku 2018 i 2013. Przedstawia tylko najważniejsze partie.

```{r, warning=FALSE}
df <- read.csv("./data.csv")
df$pp <- factor(df$pp, levels=df$pp)
df$elections2013 <- df$elections2018 - df$change
df <- df[, !(names(df) == "change")]
df <- melt(df, id.vars="pp")
df$variable <- factor(df$variable, levels=c("elections2018", "elections2013"), labels=c("2018", "2013"))
ggplot(df, aes(x=pp, y=value, fill=pp, alpha=variable)) +
  geom_bar(stat='identity', position='dodge') +
  scale_fill_manual(values = c("#008AC5", "#64A12D", "#007E82", "#009EE0", "#EB001F", "#FFED00", "#BE3075")) +
  scale_alpha_ordinal(range=c(1, 0.5), name="Elections") +
  geom_hline(yintercept = 5, linetype="dashed") + 
  geom_text(aes(7,5,label = "threshold", vjust = -1), show_guide  = F, size = 4) +
  labs(x = "Political party", y="Percent of votes", fill="Political party", alpha="Elections") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```