---
title: "rCharts"
author: "Damian Kisieliński"
date: "November 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
require(grid)
library(rCharts)
library(reshape2)
```

```{r, include=FALSE}
df <- data.frame(aktywa=rep(c("Aktywa obrotowe", "Zapasy"), each=5),
                rok=rep(seq(2014,2018),2),
                wartosc=c(902.9, 968.1, 1017.7, 1082.9, 1175.3, 254.4, 268.4, 275.1, 300.2, 329.9))
df
```

### PD1 ggplot2  

```{r, echo=FALSE}
ggplot(data=df, aes(x=rok, y=wartosc, fill=aktywa)) +
  geom_bar(stat="identity", position=position_dodge())+
  geom_text(aes(label=wartosc), vjust=-0.5,
            position = position_dodge(0.9), size=3.5)+
  scale_fill_manual("legend", values = c("Aktywa obrotowe" = "#756bb1", "Zapasy" = "#bcbddc"))+
  scale_y_continuous(breaks = seq(0, 1200, 100)) +
  theme_minimal() +
  theme(legend.position="bottom", axis.title = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(
          margin = margin(r = 60, unit = "pt")),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank())+
  labs(tag="")+
  ggtitle("Aktywa obrotowe na koniec czerwca w latach 2014–2018")
grid.text("mld zł", x=unit(0.03,"npc"),y=unit(0.91,"npc"),gp = gpar(fontsize = 10))
```

### PD1 rCharts

```{r, results='asis', echo=FALSE}
p2 = nPlot(wartosc ~ rok, group = 'aktywa', data = df, type = 'multiBarChart')
p2$chart(color = c('#756bb1', '#bcbddc'))
p2$show('inline', include_assets = TRUE, cdn = TRUE)
```

```{r include=FALSE}
dane <- read.csv("dane.csv", sep = ";")
datm<-melt(dane, id.vars = "miasto")       
names(datm) <- c("miasto", "rynek", "cena")
dane$miasto <- factor(dane$miasto, levels = dane$miasto[order(dane$pierwotny)])
```

### PD2 ggplot2
```{r echo=FALSE}
ggplot(data = datm,aes(x = miasto, y = cena, fill = rynek))+
  geom_bar(stat = "identity", width =  0.8, position=position_dodge())+
  scale_fill_brewer(palette="Paired")+
  theme_minimal() +
  labs(title="Przeciętne ceny za mkw. mieszkania w największych miastach Polski na rynku wtórnym i pierwotnym", x="miasto", y = "średnia cena za mkw. (w zl)") +
  theme(axis.text.x = element_text(angle = 45)) 
```

### PD2 rCharts

```{r, results='asis', echo=FALSE}
x1 = hPlot(cena ~ miasto, data = datm, type = c('bar'),group = 'rynek')
x1$show('inline', include_assets = TRUE, cdn = TRUE)
```