---
title: "Zadanie domowe 05 - Tomasz Klonecki"
author: "Tomasz Klonecki"
date: "19 November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Wstęp

W mojej pracy postanowiłem sprawdzić w jaki sposób można manipulować wykresami poprzez zmianę skali. Praca pokaże, że czytelnicy nie za bardzo zwracają uwagę na liczby - a raczej na kształty.

Dane dotyczą sprzedaży poszczególnych modeli telefonów w Wielkiej Brytanii w Lutym 2018.

Ankieta do pracy: [link](https://goo.gl/forms/f4sHBZpcNuuOMX952)

# Przedstawienie wykresów
```{R, echo = FALSE}
library(ggplot2)

options(stringsAsFactors=FALSE)

phone <- c("Apple\n iPhone X",
           "Apple\n iPhone 8",
           "Apple\n iPhone 7",
           "Apple\n iPhone 8\n Plus ",
           "Xiaomi\n Redmi 5A",
           "Samsung\n Galaxy S8",
           "Samsung\n Galaxy J7",
           "vivo Y75",
           "Xiaomi\n Mi A1",
           "OPPO\n R11s")
perc <- c(5.5,3.1,2.2,1.9,1.9,1.4,1.3,1.2,1.1,1.1) + 1.0
company <- c("Apple","Apple","Apple","Apple","Xiaomi","Samsung","Samsung","vivo","Xiaomi","OPPO")

df <- data.frame(phone,perc,company)
df <- df[order(-df$perc), ]
```

### Poprawny wykres

Poniższy wykres jest dobrze zaprojektowany, skala osi OY zaczyna się w zerze, kolory są dobrze dobrane i nie ma problemu z poprawnym odczytaniem danych.

```{R, echo = FALSE, warning = FALSE}
p2 <- ggplot(data = df, aes(x = reorder(phone, -perc), y = perc, fill = company)) +
  geom_bar(stat = "identity") +
  coord_cartesian(ylim=c(0,7), expand = c(0,0)) +
  scale_fill_manual(values=c("royalblue2","darkolivegreen4", "purple3","turquoise2", "darkorange2")) +
  theme_minimal() +
  labs(x = "Smartphone Model", y = "Market share [%]") +
  ggtitle("Smartphone market share in UK during first quarter of 2018") +
  theme(
    legend.title = element_blank(),                       # usun tytul legendy
    legend.text = element_text(size = 13),                # ustawienia labeli legendy
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    axis.text.x = element_text(size = 8),                # ustawienia labeli przy osi x
    axis.text.y = element_text(size = 11)
  )
p2
```


### Wykres poddany manipulacji

Podczas tworzenia tego wykresu, wczułem się w pracownika PR firmy Apple i chciałem przedstawić dane jak najbardziej na korzyść mojej firmy. Manipulacja polega na zmianie skali OY, w taki sposób żeby słupki zaczynały się w 2. Oprócz tego zmiana kolorów, tak żeby firma Apple rzucała się w oczy.

```{R, echo = FALSE, warning = FALSE}
p1 <- ggplot(data = df, aes(x = reorder(phone, -perc), y = perc, fill = company)) +
  geom_bar(stat = "identity") +
  coord_cartesian(ylim=c(2,7), expand = c(0,0)) +
  scale_fill_manual(values=c("royalblue2","gray70", "gray61","gray80", "gray47")) +
  theme_minimal() +
  labs(x = "Smartphone Model", y = "Market share [%]") +
  ggtitle("Smartphone market share in UK during first quarter of 2018") +
  theme(
    legend.title = element_blank(),                       # usun tytul legendy
    legend.text = element_text(size = 13),                # ustawienia labeli legendy
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    axis.text.x = element_text(size = 8),                # ustawienia labeli przy osi x
    axis.text.y = element_text(size = 11)
    )
p1
```

# Wyniki ankiety

Do obu wykresów zostało zadane takie samo pytanie, mające na celu sprawdzić czy czytelnik zobaczy, że ma do czynienia z tymi samymi danymi, tylko przedstawionymi w inny sposób. W idealnej sytuacji (kiedy wszyscy zauważyliby że dane są takie same i próbuję ich oszukać) stosunek odpowiedzi dla obu wykresów powinien pozostać taki sam. Jak można się spodziewać tak się nie stało. Poniżej prezentuje wykres, który przedstawia procentowy udział odpowiedzi na pytanie dotyczące obu wykresów (Prawidłowego i Zmanipulowanego). W ankiecie wzieły udział 33 osoby.

```{R,echo = FALSE}
Odpowiedz <- c("Telefony firmy Apple\n kompletnie zdominowały rynek","Firma Apple niezbyt\n znacząco wyprzedziła inne","Ciężko powiedzieć","Telefony firmy Apple\n kompletnie zdominowały rynek","Firma Apple niezbyt\n znacząco wyprzedziła inne","Ciężko powiedzieć")
Procenty <- c(87.9,9.1,3,60.6,30.3,9.1)
Typ <- c("Prawidłowy","Prawidłowy","Prawidłowy","Manipulacja","Manipulacja","Manipulacja")
df2 <- data.frame(Odpowiedz,Typ,Procenty)    
p2 <- ggplot(df2, aes(x = Odpowiedz, y = Procenty, group = Typ)) + geom_bar(aes(fill = Typ), position = "dodge", stat="identity") +
  coord_flip() +
  geom_text(aes(label=Procenty), position=position_dodge(width=0.9)) +
  labs(x = "", y = "% danej odpowiedzi")+
  ggtitle("Jak oceniasz stosunek sprzedaży\nposzczególnych telefonów marki iPhone do pozostałych")+
  theme_minimal() +
  theme(
    legend.title = element_blank(),                       
    legend.text = element_text(size = 13),
    axis.title.x = element_text(size = 14),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 10)
  )
p2
```

# Wnioski

W wybranych przeze mnie danych, nie było łatwo oszukać czytelników, ponieważ dane tak czy siak pokazywały przewagę Apple nad innymi firmami. Jednak w dalszym ciągu znalezli się ludzie, którzy nie zwracali uwagi na osie wykresu. Na podstawie odpowiedzi w ankiecie można powiedzieć, że około 20-30 % (co 4-5 osoba) dała się nabrać na prosty trik, polegający na zmianie osi OY.

Na podstawie tych wniosków, mogę jeszcze tylko dodać, że jeżeli ktoś sprawnie operuje wykresami i wie jak nimi manipulować, tak aby zwykły odbiorca się nie połapał - może zdziałać cuda!