---
title: "Praca domowa nr 4"
author: "Prokopczuk Magda"
date: "7 listopada 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dane wykorzystane do wykresu pochodzą z artykułu dostępnego pod linkiem  https://www.thebalance.com/halloween-spending-statistics-facts-and-trends-3305716. 

## Wykres czarno-biały
```{r czarno}
Rok<-as.factor(2012:2018)
Liczba<-c(170,158,162,157,171,179,175)
df<-data.frame("Rok"=Rok, "Liczba"=Liczba)
library(ggplot2)
ggplot(df, aes(x=Rok, y=Liczba, fill = factor(-Liczba), label=Liczba)) + 
  geom_col(position = "dodge", width = 0.8) +
  geom_text(vjust = -0.4, position = position_dodge(width = 0.8)) +
  xlab("Rok") + 
  ylab("Liczba Amerykanów (w mln)") +
  ggtitle("Liczba Amerykanów świętujących Halloween") +
  theme_bw() +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(size = rel(1.3), vjust=7),
        plot.title =  element_text(size = rel(1.5)))  +
  scale_fill_grey() +
  guides(fill=FALSE)
```

## Wykres kolorowy
```{r kolor}

ggplot(df, aes(x=Rok, y=Liczba, fill = factor(Liczba), label=Liczba)) + 
  geom_col(position = "dodge", width = 0.8) +
  geom_text(vjust = -0.4, position = position_dodge(width = 0.8)) +
  xlab("Rok") + 
  ylab("Liczba Amerykanów (w mln)") +
  ggtitle("Liczba Amerykanów świętujących Halloween") +
  theme_bw() +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(size = rel(1.3), vjust=7),
        plot.title =  element_text(size = rel(1.5)))  +
  scale_fill_brewer(palette = "YlOrBr") +
  guides(fill=FALSE)
```