---
title: "Praca domowa nr 1 - TWD"
author: "Szymon Maksymiuk"
date: "16 października 2018"
output: html_document
---

# Wstęp

Tknięty szałem wyborczym i wszechobecnymi sondażami mającymi przedstawiać poparcie, postanowiłem pozostać w temacie polityki przy wykonywaniu zadania. Z pomocą przyszedł mi CBOS, a konkretniej mówiąc, artykuł w poratlu interia.pl (https://fakty.interia.pl/polska/news-ocena-prezydenta-najnowszy-sondaz-cbos,nId,2645166) opisujący jeden z kolejnych sondaży Centrum. Dodatkowo, czytając artykuł, ze zgrozą przekonałem się o tym, że nie załączono do niego wykresu, stąd też postanowiłem to natychmiast naprawić. Pragnę w tym punkcie zaznaczyć, że wszystkie dane czerpałem z tego artykułu, nie starałem się poprawiać ewidentych błędów takich jak nie sumowanie się punktów procentowych przy Panu Prezydencie do stu oraz brak kategorii "Nie mam zdania" dla samorządu. Na słowo uwagi zasługuje również forma. Zastanawiałem się dłuższy czas czy nie użyć wykresu słupkowego skumulowanego lecz odstąpiłem od tego z dwóch powodów. Po pierwsze będne dane sprawiłyby, że całość wyglądałaby nie najlepiej, po drugie zaś. do sondaży pasują mi tylko i wyłącznie wykresy słupkowe, tak się je przecież zazwyczaj w mediach przedstawia.

# Wykonanie zadania


```{r fig.width=12, fig.height=6}
library(ggplot2)

dane <- data.frame(rbind(c("PAD", "le", 31),
                         c("PAD", "Nie mam zdania", 10),
                         c("PAD", "Dobrze", 56),
                         c("Sejm", "le", 52),
                         c("Sejm", "Nie mam zdania", 17),
                         c("Sejm", "Dobrze", 31),
                         c("Senat", "le", 44),
                         c("Senat", "Nie mam zdania", 25),
                         c("Senat", "Dobrze", 31),
                         c("Samorząd", "le", 23),
                         c("Samorząd", "Dobrze", 70)))

colnames(dane) <- c("Kandydat", "Kategoria", "Wynik")

dane$Wynik <- as.numeric(as.vector(dane$Wynik))
ggplot(data=dane, aes(x=Kandydat, y=Wynik, fill=Kategoria)) +
geom_bar(stat="identity", width = 0.8, position = position_dodge(width = 0.9), colour="black")+
geom_text(aes(label=Wynik), vjust=1.6, color="black",
          position = position_dodge(0.9), size=3.5)+
ylim(0,max(dane$Wynik)+5)+
scale_fill_brewer(palette="Set1")+
labs(x="", y="Wynik (%)", fill = "")+
ggtitle("Oceny działalności parlamentu, prezydenta i władz lokalnych. CBOS październik 2018")+
theme_minimal()+
theme(plot.title = element_text(hjust = 0.5))

```



